const $=id=>document.getElementById(id);
const state={files:[],selected:new Set(),contents:{},changes:{}};
function loadSettings(){ $('ghToken').value=localStorage.getItem('ghToken')||''; $('geminiKey').value=localStorage.getItem('geminiKey')||''; $('geminiModel').value=localStorage.getItem('geminiModel')||'gemini-2.5-flash'; $('modelLabel').textContent=$('geminiModel').value; }
loadSettings();
$('settingsBtn').onclick=()=>{loadSettings();$('settingsDialog').showModal()};
$('saveSettings').onclick=()=>{localStorage.setItem('ghToken',$('ghToken').value.trim());localStorage.setItem('geminiKey',$('geminiKey').value.trim());localStorage.setItem('geminiModel',$('geminiModel').value.trim()||'gemini-2.5-flash');$('modelLabel').textContent=localStorage.getItem('geminiModel');};
function ghHeaders(){return {'Accept':'application/vnd.github+json','Authorization':'Bearer '+localStorage.getItem('ghToken'),'X-GitHub-Api-Version':'2026-03-10'}}
async function gh(path,opt={}){let r=await fetch('https://api.github.com'+path,{...opt,headers:{...ghHeaders(),...(opt.headers||{})}});let t=await r.text();if(!r.ok)throw Error(`GitHub ${r.status}: ${t}`);return t?JSON.parse(t):null}
$('loadBtn').onclick=async()=>{try{if(!localStorage.getItem('ghToken'))throw Error('Open Settings and add a GitHub token first.');let repo=$('repo').value.trim(),branch=$('branch').value.trim();if(!repo.includes('/'))throw Error('Use owner/repository.');$('loadStatus').textContent='Loading repository tree…';let d=await gh(`/repos/${repo}/git/trees/${encodeURIComponent(branch)}?recursive=1`);state.files=d.tree.filter(x=>x.type==='blob'&&x.path.endsWith('.py')).map(x=>x.path);state.selected=new Set(state.files);renderFiles();$('analyzeBtn').disabled=state.files.length===0;$('loadStatus').textContent=`Loaded ${state.files.length} Python files.`}catch(e){$('loadStatus').textContent=e.message}};
function renderFiles(){ $('files').innerHTML=state.files.map((p,i)=>`<label class="file"><input type="checkbox" data-i="${i}" ${state.selected.has(p)?'checked':''}> <span>${escapeHtml(p)}</span></label>`).join('');document.querySelectorAll('.file input').forEach(x=>x.onchange=()=>{let p=state.files[+x.dataset.i];x.checked?state.selected.add(p):state.selected.delete(p);}); }
$('selectAll').onclick=()=>{state.files.forEach(p=>state.selected.add(p));renderFiles()};
async function getFile(repo,path,branch){let d=await gh(`/repos/${repo}/contents/${path}?ref=${encodeURIComponent(branch)}`);let bytes=Uint8Array.from(atob(d.content.replace(/\n/g,'')),c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function gemini(prompt){let key=localStorage.getItem('geminiKey');if(!key)throw Error('Open Settings and add a Gemini API key first.');let model=localStorage.getItem('geminiModel')||'gemini-2.5-flash';let r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.1,responseMimeType:'application/json'}})});let t=await r.text();if(!r.ok)throw Error(`Gemini ${r.status}: ${t}`);let j=JSON.parse(t),text=j.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';return JSON.parse(text.replace(/^```json\s*|\s*```$/g,''))}
$('analyzeBtn').onclick=async()=>{try{let repo=$('repo').value.trim(),branch=$('branch').value.trim(),paths=[...state.selected];if(!paths.length)throw Error('Select at least one file.');$('analyzeBtn').disabled=true;$('agentStatus').textContent='Downloading selected files…';state.contents={};for(const p of paths)state.contents[p]=await getFile(repo,p,branch);let payload=Object.entries(state.contents).map(([p,c])=>`\n===== ${p} =====\n${c}`).join('\n');let prompt=`You are a careful repository repair agent. User instruction: ${$('instruction').value.trim()||'Find and fix clear correctness bugs while preserving public behavior.'}\n\nSelected Python files:\n${payload}\n\nReturn ONLY JSON with keys summary (string) and changed_files (object mapping file path to COMPLETE replacement file contents). Only change selected files. Do not add secrets, malware, credential theft, persistence, destructive commands, or unrelated functionality. Preserve APIs unless required. If a file needs no change, omit it.`;$('agentStatus').textContent='Gemini is analyzing and preparing a patch…';let result=await gemini(prompt);state.changes=result.changed_files||{};$('summary').innerHTML=`<p>${escapeHtml(result.summary||'Changes proposed.')}</p>`;$('changes').innerHTML=Object.entries(state.changes).map(([p,c])=>`<details class="change" open><summary>${escapeHtml(p)}</summary><pre class="code">${escapeHtml(c)}</pre></details>`).join('')||'<p>No changes proposed.</p>';$('review').classList.remove('hidden');$('agentStatus').textContent=`Proposed changes in ${Object.keys(state.changes).length} file(s). Review before committing.`}catch(e){$('agentStatus').textContent=e.message}finally{$('analyzeBtn').disabled=false}};
$('commitBtn').onclick=async()=>{try{let repo=$('repo').value.trim(),branch=$('branch').value.trim(),paths=Object.keys(state.changes);if(!paths.length)throw Error('No changes to commit.');if(!confirm(`Commit ${paths.length} changed file(s) to ${repo}:${branch}?`))return;$('commitStatus').textContent='Creating Git objects and commit…';let ref=await gh(`/repos/${repo}/git/ref/heads/${encodeURIComponent(branch)}`);let parent=ref.object.sha;let commit=await gh(`/repos/${repo}/git/commits/${parent}`);let entries=[];for(const p of paths){let blob=await gh(`/repos/${repo}/git/blobs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:state.changes[p],encoding:'utf-8'})});entries.push({path:p,mode:'100644',type:'blob',sha:blob.sha});}let tree=await gh(`/repos/${repo}/git/trees`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({base_tree:commit.tree.sha,tree:entries})});let message=$('commitMessage').value.trim()||'AI Repo Agent: repair selected files';let newCommit=await gh(`/repos/${repo}/git/commits`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,tree:tree.sha,parents:[parent]})});await gh(`/repos/${repo}/git/refs/heads/${encodeURIComponent(branch)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({sha:newCommit.sha,force:false})});$('commitStatus').textContent=`Committed successfully: ${newCommit.sha.slice(0,12)}`;}catch(e){$('commitStatus').textContent=e.message}}
